// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMUP38IJ0Uht9_8lvs954aBmiN_2PAHw',
    appId: '1:390448277963:web:fbad02d983c88c74f06e4e',
    messagingSenderId: '390448277963',
    projectId: 'psm-uthmshareride',
    authDomain: 'psm-uthmshareride.firebaseapp.com',
    storageBucket: 'psm-uthmshareride.firebasestorage.app',
    measurementId: 'G-ZQTV427NK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKkVVHL_VbL1DZMYtPwpMEmJLpRGRfhh0',
    appId: '1:390448277963:android:aa2ccfac6604072ff06e4e',
    messagingSenderId: '390448277963',
    projectId: 'psm-uthmshareride',
    storageBucket: 'psm-uthmshareride.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEaiJrXl9ImRlpt5kZz86WJXTUA66leHM',
    appId: '1:390448277963:ios:1a6927d110895115f06e4e',
    messagingSenderId: '390448277963',
    projectId: 'psm-uthmshareride',
    storageBucket: 'psm-uthmshareride.firebasestorage.app',
    iosBundleId: 'com.example.uthmshareride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEaiJrXl9ImRlpt5kZz86WJXTUA66leHM',
    appId: '1:390448277963:ios:1a6927d110895115f06e4e',
    messagingSenderId: '390448277963',
    projectId: 'psm-uthmshareride',
    storageBucket: 'psm-uthmshareride.firebasestorage.app',
    iosBundleId: 'com.example.uthmshareride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGMUP38IJ0Uht9_8lvs954aBmiN_2PAHw',
    appId: '1:390448277963:web:519db92e3bb8f390f06e4e',
    messagingSenderId: '390448277963',
    projectId: 'psm-uthmshareride',
    authDomain: 'psm-uthmshareride.firebaseapp.com',
    storageBucket: 'psm-uthmshareride.firebasestorage.app',
    measurementId: 'G-6H2EDZFYQ4',
  );
}
